{% extends "layout.phtml" %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<h1>Gifiding</h1>
		<ol>
			<li>Select a GIF</li>
			<li>Select an overlay</li>
			<li>Hit 'upload'</li>
		</ol>
		<form class="form" id="upload-form">
			<label>GIF</label>
			<input type="file" name="gif" accept="image/gif">
			<br/>
			<label>Overlay</label>
			<input type="file" name="overlay" accept="image/*">
			<br/>
			<input class="btn" type="submit" value="upload">
		</form>
		<p id="error-text" class="text-danger"></p>
		<br/><br/>
		<img id="output-image" src="">
		<p id="help" style="display:none;"><em>Click on the image to move the overlay</em></p>
	</div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
	$(function() {
		$('#upload-form').submit(function(e) {
			e.preventDefault();
			$("#error-text").html('');
			$.ajax({
				url: '{{backend_host}}/upload',
				type: 'POST',
				headers: {Authorization: 'Bearer '+getCookie('jwt')},
				data: new FormData(this),
				processData: false,
				contentType: false
			}).success(function() {
				refreshImage(0, 0);
			}).error(function(err) {
				if (err.statusCode == 401) {
					window.location = "/login";
				}
				$("#error-text").html(err.statusText);
			});
		});

		$("#output-image").click(function(e) {
			refreshImage(e.offsetX*-1, e.offsetY*-1);
		});
	});

	function refreshImage(x, y) {
		$("#error-text").html('');
		$.ajax({
			url: '{{backend_host}}/img?x='+x+'&y='+y,
			headers: {Authorization: 'Bearer '+getCookie('jwt')},
			processData : false,
		}).success(function(b64data){
			$('#help').show();
			$("#output-image").attr("src", "data:image/png;base64,"+b64data);
		}).error(function(err) {
			$('#help').hide();
			if (err.statusCode == 401) {
				window.location = "/login";
			}
			$("#error-text").html(err.statusText);
		});
	}

	function getCookie (sKey) {
		if (!sKey) { return null; }
		return decodeURIComponent(document.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*" + encodeURIComponent(sKey).replace(/[\-\.\+\*]/g, "\\$&") + "\\s*\\=\\s*([^;]*).*$)|^.*$"), "$1")) || null;
	}

</script>
{% endblock %}