{% extends "layout.phtml" %}

{% block content %}
<div class="row">
	<div class="col-md-12">
		<h1>Login</h1>
		<form method="POST">
			<div class="form-group">
			<label for="username">Username</label>
			<input type="text" class="form-control" name="username" placeholder="Username">
			</div>
			<div class="form-group">
				<label for="password">Password</label>
				<input type="password" class="form-control" name="password" placeholder="Password">
			</div>
			<p class="text-danger">{{ error }}</p>
			<button type="submit" class="btn btn-default">Login</button>
		</form>
		<br/>
		<p class="pull-right"><a href="/register">Register</a></p>
	</div>
</div>
{% endblock %}
